### ISSUE TITLE
toggle sub-directory support in posts and pages

### ISSUE THREAD

**Issue by chadhs** [cryogen-project/cryogen-core#107]
@matsu911 @lacarmen would you be open to / is there a way we can make sub-directory support in posts and pages a toggle in the config.edn? in `0.1.38`  i used to rely on the fact that subdirs were searched for posts but not reflected in the url.

example: `/posts/2016/cool-post.md` would yield a url of `/cool-post` but now yields a url of `/2016/cool-post`

being able to group posts by year was a nice way to organize without having the date in the url.
https://github.com/cryogen-project/cryogen-core/commit/510c33c23d587f2b6d335689aff596a051a6346a

**Comment by lacarmen** [comment]
@chadhs Sure, that looks like an easy change. I can try to take a look at this in a week or so but I'd be open to a PR as well. :)

**Comment by chadhs** [comment]
^ an initial swing at tackling this.

**Comment by lacarmen** [comment]
Fixed in #108 (new snapshot deployed on clojars, but not in the template yet)
