### ISSUE TITLE
Dart/Js Sass compilation breaks: "--update is not allowed when printing to stdout"

### ISSUE THREAD

**Issue by KingMob** [cryogen-project/cryogen-core#111]
I'm seeing an error now, where sass complains "--update is not allowed when printing to stdout". It happens for both Dart Sass and Js Sass, it seems. The original Ruby Sass still works, but it's been deprecated: https://sass-lang.com/ruby-sass

Versions:
Cryogen-core 0.1.61
Dart Sass: 1.4.0

**Comment by lacarmen** [comment]
There is an [issue](https://github.com/sass/dart-sass/issues/264) open in the dart sass project right now to make the `--update` flag available. 

I've been keeping up with it and it looks like it's making good progress so I'm just going to sit tight for now.

**Comment by KingMob** [comment]
OK. Maybe we should add something to the FAQ/wiki/docs for the time being?

**Comment by neominik** [comment]
The referenced issue is closed now. Result: same error message, because the usage of the sass command has changed. It has to be called as `sass --update input-dir:output-dir`

I will prepare a pull request with a fix (not sure about compass though).

**Comment by fahdkh** [comment]
I still have the same problem. what could possibly be I am doing wrong?

**Comment by fahdkh** [comment]
Dart Sass 1.14.1

**Comment by lacarmen** [comment]
Can you try with `cryogen-core 0.1.63` please?

**Comment by fahdkh** [comment]
Yay! It works now! Thanks.
