### ISSUE TITLE
Support for GFM tables

### ISSUE THREAD

**Issue by devth** [cryogen-project/cryogen-core#114]
With a quick look I couldn't figure out which lib is doing the markdown compiling. I'm guessing table support would be based on whether our markdown compiler supports it.

[GFM Tables](https://github.github.com/gfm/#tables-extension-)

**Comment by lacarmen** [comment]
Cryogen uses a [plugin system](http://yogthos.net/posts/2015-01-15-A-Plugin-System-in-Clojure.html) for loading different markup compilers. The leiningen template defaults to `cryogen-markdown` which in turn uses `markdown-clj`. 

I think it supports GFM tables (at least according to the [demo site](https://rawgit.com/yogthos/markdown-clj/master/demo/markdown.html)) but if it doesn't you could try switching it out for a different compiler.

**Comment by devth** [comment]
Yep demo site looks good. I'm not sure why it didn't render correctly for me. Will investigate further. Thanks.
