### ISSUE TITLE
config based themes

### ISSUE THREAD

**Issue by yogthos** [cryogen-project/cryogen-core#12]
- pull out hardcoded template variables into config
- provide a way to select themes from using a config variable
- fetch themes from github using theme name?

**Comment by zerg000000** [comment]
Agree.

I have some thoughts on this topic.

### Pull out hardcoded template variables into config as default config.

```{clojure}
            (render-file "templates/html/layouts/page.html" ;should be read from config
                         (merge params
                                {:servlet-context "../"
                                 :page            page
                                 :uri             uri}))
```
### Select themes by using config.

#### Add themes folder for containing themes

`templates/html` -> `templates/themes/default/html`

#### Lookup theme by the theme name in config

This line in `config.edn`

```{clojure}
{:theme "blues"}
```

#### Override `config.edn` config by page/post's metadata

`config.edn`

```{clojure}
{:theme "blues"}
```

`posts/2015-12-12-a-different-look-and-feel-post.asc`

```{clojure}
{:theme "yoga" } ; this line will override the one in config.edn
```

"yoga" theme should be used to generate the blog post.

### Fetch themes from github

#### Create a central repository for lookup theme

    cryogen-project/cryogen-themes

#### Add leiningen plugin `lein-cryogen-theme` to template project

The plugin should provide following commands

 task   | subtask | description
---------|------------|----------------
theme | list                                  | list the themes on `cryogen-project/cryogen-themes`
theme | add [theme-name] or [theme-github-url]   | download the theme to `templates/themes`
theme | remove theme-name                                 | remove the theme from `templates/themes`

Is it good for implementing your idea like this?

**Comment by lacarmen** [comment]
Yes, I think this is a good way to do it. I've merged your pr and made a few fixes for the config based theme stuff in 4511536cc9ba687e417b68c75b1ad41cb3809e77. 

The project structure has been changed slightly. I'll have to reflect that in the documentation.

I'm going to leave this issue open until I add some more themes

**Comment by zerg000000** [comment]
great! we should add some documentation for migrating from 0.21 to 0.22.

**Comment by LauriListak** [comment]
Would it be possible to somehow specify additional folders in a theme file? Because right now it seems that only 'css/', 'js/' and 'html/' folders are pulled in from a theme. The current use case is to include additional fonts and images, that can be specific to a theme.

**Comment by lacarmen** [comment]
You can add your resources in the theme folder and then specify then in the `:resources` parameter inside `config.edn`. The compiler should copy them over to the output folder

**Comment by KingMob** [comment]
Slight update, if anyone's still reading. As of 0.1.57, themes can have their own config.edn file that gets merged with the main config, so they can specify additional directories for things like `:resources`.

**Comment by harlanji** [comment]
I've been with Cryogen since about 0.1.60 and always known the last comment to be true and have utilized it; and I see 0.1.22 and 0.1.57 as the latest versions mentioned. Is there reason for this ticket to be open?

**Comment by lacarmen** [comment]
> Is there reason for this ticket to be open? 

I guess not. The themes are swappable via config right now, but they don't pull from Github -- all of them are included when you create a Cryogen project through Leiningen. I don't see that as a problem, so let's close this.
