### ISSUE TITLE
Changing `:public-dest` seems to break CSS/JS access

### ISSUE THREAD

**Issue by NicMcPhee** [cryogen-project/cryogen-core#121]
I switched the value of `:public-dest` from `public` to `docs` and the contents of `docs/css` and `docs/js` have now become invisible. I'm using the "blue" theme, and `screen.css` doesn't load anymore. Ditto for `highlight.pack.js`. The files are there in `docs/css` and `docs/js`, but they're not found by the browser.

Any idea why that's happening?

Thanks in advance.

**Comment by lacarmen** [comment]
Just to clarify, this is happening when you run the server locally? If so, I suspect [this](https://github.com/cryogen-project/cryogen/blob/master/src/leiningen/new/cryogen/src/cryogen/server.clj#L19) probably needs to be updated.

**Comment by NicMcPhee** [comment]
Sorry for being slow to get back to you.

Yes, it was indeed when I was running the server locally, and I do seem to remember that there were some weird things with slashes, so your suspicion seems plausible to me.

**Comment by lacarmen** [comment]
Thanks for confirming. I'll try to fix it this week :)

**Comment by lacarmen** [comment]
Sorry I dropped the ball on this @NicMcPhee. I couldn't actually reproduce the problem... If this is still an issue for you could you provide more details?

**Comment by lacarmen** [comment]
Oh wait, I *can* reproduce it 😄 I didn't get an error about missing resources and had stuff cached so was confused. Working on a fix now.

**Comment by lacarmen** [comment]
Should be fixed in the latest version of the template. I just checked if the link ends in `/` or `.html` before doing the magic with the slashes. It's not perfect and there may be another weird case in the future but I'm hoping this covers the majority of cases.
