### ISSUE TITLE
Provide :preview-plaintext to every post, page for SEO

### ISSUE THREAD

**Issue by holyjak** [cryogen-project/cryogen-core#125]
Make the "preview" of a page/post available to it as plain text so that it can be included in `<meta name="description" content=...>` and similarly in `og:description` etc to show nice previews in Slack, Fb etc and provide better SEO.

I'd be happy to make a PR for this, likely using the existing html previews and extracting the plain text from them using Enlive or JSoup.

**Comment by lacarmen** [comment]
Addressed by #126 and cryogen-project/cryogen#195
