### ISSUE TITLE
Provide an option to drop the date from file names

### ISSUE THREAD

**Issue by holyjak** [cryogen-project/cryogen-core#128]
Having a file like `content/asc/posts/2019-03-21-awesome-post.asc` generates `public/<posts-root-uri>/2019-03-21-awesome-post.html` however I want it without the date, i.e. `awesome-post.html` (so that I don't break all URLs after migrating to Cryogen - and I prefer the dates in the source file name as they are nicely sorted by it).

A solution would be to add `:post-remove-date true` (or `post-dateless-uri`)?

I'd be happy to provide a PR.

**Comment by lacarmen** [comment]
PRs always welcome!

**Comment by holyjak** [comment]
Deprecated by #130 that makes it possible for the user to do it herself, as shown at http://cryogenweb.org/docs/customizing-cryogen.html#extra_parameters_for_your_selmer_templates
