### ISSUE TITLE
Bug: cannot set a page as homepage

### ISSUE THREAD

**Issue by ir-regular** [cryogen-project/cryogen-core#135]
**Attempted**: adding a `:home? true` flag to a page.

**Problem observed**: page contents don't render.

Reproducible on a fresh cryogen install (screenshot attached.)

**Cause**:

1. in `params`, `:home-page` may contain either a page or a post map.
2. `compile-index` extracts `:home-page` and re-attaches it to `params` as both `:post` and `:page`, then passes the resulting map to `render-file` - [see code](https://github.com/cryogen-project/cryogen-core/blob/9e4dc9f6cdbba3123f2f5ded3307c55cffef8860/src/cryogen_core/compiler.clj#L449).
3. `render-file` calls `htmlize-content`
4. in `htmlize-content`, `cond` short-circuits after finding `:post` and never htmlizes `:page` - [see code](https://github.com/cryogen-project/cryogen-core/blob/9e4dc9f6cdbba3123f2f5ded3307c55cffef8860/src/cryogen_core/compiler.clj#L272)
5. back to `compile-index` - it selects the correct layout via `(:layout home-page)`, and the layout attempts to print `page.content`, which has not been created in the previous step

**Some options for a fix:**

- update `htmlize-content` to use `cond->` instead of `cond`, and fix all available keys
- fix `compile-index` so that it includes either a `:post` or a `:page` but not both (pages contain :page-index while posts don't)
- have page and post maps contain `:type :page` or `:type :post` and have `compile-index` merge `(:type home-page) home-page` into params

<img width="751" alt="homepage-about" src="https://user-images.githubusercontent.com/13539395/72633145-bdef5600-394f-11ea-97a7-25cfe90b81e2.png">

**Comment by lacarmen** [comment]
Thanks for the detailed report @ir-regular  :)
