### ISSUE TITLE
Tags with special characters get a broken tag-output page. Like tag C#

### ISSUE THREAD

**Issue by gamlerhart** [cryogen-project/cryogen-core#142]
A tag with a special characters create a broken tag-output page. The link to the tag page contains the character 1:1 and then cannot be found on the server. In my example I've a tag C#, which leads to the tags-output/C# page, which is then interpreted as a link to an achor.

Suggested fix: URL encode the tag links.

**Comment by gamlerhart** [comment]
Suggested fix: https://github.com/cryogen-project/cryogen-core/pull/143 
Maybe there is another idea how to fix it?

**Comment by bombaywalla** [comment]
This issue was fixed by #143 so closing this issue.
