### ISSUE TITLE
<!-more-> marker characters

### ISSUE THREAD

**Issue by daverclarke** [cryogen-project/cryogen-core#151]
Hi,

I've just upgraded from an older version of cryogen to 0.3.2 and the more marker as a preview break stopped working.  I still see "<!–more–>" in the documentation, but it doesn't seem to be working.

**Comment by holyjak** [comment]
It works for me (using cryogen-asciidoc and wrapping it with `+++`). What version have you upgraded from?

**Comment by daverclarke** [comment]
Aha,

The two dashes is probably the difference as that does work. I'm coming from 0.2.1 to the current version.  I do notice on the doco page (http://cryogenweb.org/docs/customizing-the-index.html) it still lists the single dash <!-more-> as the break.

**Comment by holyjak** [comment]
# Title correction: Fix the docs to show `--` as-is

Somehow, the `--` becomes `–` (unicode 8211) so we need to fix the docs to stop doing that.

**Comment by holyjak** [comment]
The docs will be fixed once cryogen-project/cryogen-docs#33 is merged and the site rebuilt.

**Comment by lacarmen** [comment]
Thank you @holyjak ❤️
