### ISSUE TITLE
Make :posts and :pages available in all posts and pages by default

### ISSUE THREAD

**Issue by ieugen** [cryogen-project/cryogen-core#157]
Rendering a list of posts and pages is an usual requirement. 
I believe it they should be available by default when rendering templates.

I've encountered this when trying to add them: https://github.com/cryogen-project/cryogen-core/issues/156

**Comment by holyjak** [comment]
Nobody else has asked for it so I do not think it is all that common, and it is fairly simple to implement yourself - see https://github.com/holyjak/tmp-demo-cryogen-posts-everywhere/commit/0d7654f816f669b88b313c37aaeecb90d9798437
