### ISSUE TITLE
Images by theme

### ISSUE THREAD

**Issue by simon-brooke** [cryogen-project/cryogen-core#170]
See [issue on 265 Cryogen](https://github.com/cryogen-project/cryogen/issues/265).

**Comment by simon-brooke** [comment]
Further to this:

`cryogen-core/io` currently throws an exception if an expected resource is not found. 'Legacy' themes won't have the additional directories, but we'd like them still to work. So what I've implemented is printing the error message in yellow -- as a warning colour -- rather than throwing an exception. Is that acceptable?

```diff
diff --git a/src/cryogen_core/io.clj b/src/cryogen_core/io.clj
index 42ea2ad..2b77c89 100644
--- a/src/cryogen_core/io.clj
+++ b/src/cryogen_core/io.clj
@@ -2,7 +2,7 @@
   (:require [clojure.java.io :as io]
             [clojure.string :as string]
             [me.raynes.fs :as fs]
-            [text-decoration.core :refer :all]))
+            [text-decoration.core :refer [cyan red yellow]]))
 
 (def ^:dynamic public "public")
 
@@ -94,7 +94,7 @@
       (println "\t" (cyan src) "-->" (cyan target))
       (cond
         (not (.exists (io/file src)))
-        (throw (IllegalArgumentException. (str "resource " src " not found")))
+        (yellow (str "resource " src " not found"))
         (.isDirectory (io/file src))
         (copy-dir src target ignored-files)
         :else
@@ -109,5 +109,7 @@
           {:resources (concat
                        ["css"
                         "js"
+                        "img"
+                        "fonts"
                         "html/404.html"]
                        (:theme-resources config))})))
```

**Comment by simon-brooke** [comment]
(Actually, the above doesn't print the yellow text... so my current code is slightly updated. But you get the point, and the question of whether it is acceptable to print a warning and continue, rather than throwing an exception and aborting, remains)

**Comment by yogthos** [comment]
Yeah that sounds reasonable, can just be a warning in the console.
