### ISSUE TITLE
Multilevel TOC accumulator may screw up the structure if last element is not h1

### ISSUE THREAD

**Issue by kremers** [cryogen-project/cryogen-core#19]
(str acc "</ol>") does close the beginning ol, but if no h1 element are present in the last place, it may end up with unclosed elements. This can be fixed by adding (repeat (* -1 (compare_index _last :h1)) "</ol>").

**Comment by lacarmen** [comment]
Can you point out the error or submit a pull request? I don't see any `(str acc"")` in toc.clj
