### ISSUE TITLE
Modifying :post-root eliminates all posts

### ISSUE THREAD

**Issue by johnmendonca** [cryogen-project/cryogen-core#22]
Create a new cryogen project and build.

With the default settings, this will generate folder ```blog/posts``` containing all posts.

If I edit ```config.edn``` to read ```:post-root "foo"``` and rebuild, no "foo" folder is created and the original "posts" folder is also gone.  The posts are not generated:

```
$ ls blog/*
blog/404.html		blog/cryogen.xml	blog/index.html
blog/archives.html	blog/feed.xml		blog/sitemap.xml

blog/css:
asciidoc.css	screen.css

blog/js:
highlight.pack.js

blog/pages:
about.html		another-page.html
```

Also, the "tags" folder is missing.  When I restore ```:post-root "posts"``` these things return:

```
$ ls blog/*
blog/404.html		blog/cryogen.xml	blog/index.html
blog/archives.html	blog/feed.xml		blog/sitemap.xml

blog/css:
asciidoc.css	screen.css

blog/js:
highlight.pack.js

blog/pages:
about.html		another-page.html

blog/posts:
10-03-2014-first-post.html	11-04-2014-second-post.html	13-11-2014-docs.html

blog/tags:
cryogen.html	not fetch.html	very fetch.html
```

I'm seeing the same behavior for ```:page-root```.  Thanks for your work on this project.

**Comment by lacarmen** [comment]
Hey, I just wanted to check in to let you know that this issue might take me some time since life's pretty busy at the moment

**Comment by johnmendonca** [comment]
Thanks, it's no problem.  I mostly wanted to document the issue since I happened upon it.  The default names will work for me.

**Comment by johnmendonca** [comment]
I have discovered the key to using this feature.  The source folder of posts needs to have its name changed as well ```resources/templates/md/posts``` => ```resources/templates/md/foo```.

**Comment by lacarmen** [comment]
Yes, that is the case. So it works for you then?

I had originally assumed that you were changing the folder name accordingly

**Comment by johnmendonca** [comment]
Yes, you're correct.  I had thought the setting was for output structure only.
