### ISSUE TITLE
image handling in Post is generally broken

### ISSUE THREAD

**Issue by zerg000000** [cryogen-project/cryogen-core#24]
First, I have a hard time when i try to include images in markdown
, when I am following the instructions from [Including Images in Posts](http://cryogenweb.org/docs/writing-posts.html).

1. Missing resources/public/img/xxxx.jpg

    The source of the problem is the `copy-images-from-markdown-folders`  will never 
    create the folder `resources/public/img/` when it does not exist, so the `io/copy` will fail forever.
    ```clojure
    (defn copy-images-from-markdown-folders [{:keys [blog-prefix]}]
      (doseq [asset (fs/find-files "resources/templates/md" #".+(jpg|jpeg|png|gif)")]
        (io/copy asset (io/file (str public blog-prefix "/img/" (.getName asset))))))
    ```
    Finally, I avoid this bug by creating `img` folder in `resources/templates` adding this line to `config.edn`
    ```clojure
     :resources        ["css" "js" "img" "404.html"]
    ```
2. Naming conflict for posts images

    Since all posts' image will be flatten into `/img/`, the images with same name will be overwritten.

3. Not supporting all image formats which widely supported

    Bottom line, SVG should be supported by the copying function.

4. Inconsistent image handling for Asciidoc

    As the copy-images-from-markdown-folders` function name implied, only images in `/md/` folder   will be copied. This raise the question, where should I place my post's images for Asciidoc posts?

### Solution

Replace `copy-images-from-markdown-folders` with function

```clojure
(defn copy-post-assets [config] ...)
```

The function will copying posts' resources like

from                                    |                             to       
------------------------------------|-----------------------------------------------------------------                                      
`posts/goodpost/abc.png`  |  `resources/public/post-assets/goodpost/abc.png`
`posts/anotherpost/b.gif`   |  `resources/public/post-assets/anotherpost/b.gif` 
`posts/anotherpost/a.zip`   |  `resources/public/post-assets/anotherpost/a.zip`

The advantages are 

* no naming conflict 
* consistent between asciidoc and markdown
* generally apply to all file type
* open chance to support different folder structure like `/posts/2015/12/11/my-post.html`
* actually, implementation is just reuse the `copy-resources` function

**Comment by lacarmen** [comment]
I see what you're saying but post images works well enough for the majority of users right now so I'm not in a big rush to change the functionality of the copier function. 

It seems like you know what you're doing though so if you would like to submit a pull request then I'll gladly merge it in

**Comment by zerg000000** [comment]
AvisoNovate/cryogen-core seems to have all fixes in his fork.

**Comment by lacarmen** [comment]
I don't see any of the fixes that you're talking about in his fork

**Comment by lacarmen** [comment]
Scratch that, I didn't notice the branch that he made for his changes. 

He's made a lot of other changes that I do not want to include though and I don't have the time to cherry-pick my way through all the code.

**Comment by zerg000000** [comment]
pull request have been submitted.
The fix has a bit different from the previous description and might affect some of the copy-resources behaviours.

From | To
-------|---------
posts/goodpost/abc.png	| resources/public/posts/goodpost/abc.png
posts/anotherpost/b.gif	| resources/public/posts/anotherpost/b.gif
posts/anotherpost/a.zip	| resources/public/posts/anotherpost/a.zip
pages/anotherpage/abc.png | resources/public/pages/anotherpage/abc.png


So, in the markdown, the assets path for in-site references should be /< file path related to resources/templates>.

**Comment by lacarmen** [comment]
Thanks!

I've merged in your changes and did some cleanup in 4511536cc9ba687e417b68c75b1ad41cb3809e77. Also did some fixes for the config based themes. Will push out to clojars shortly

**Comment by zerg000000** [comment]
Thx
