### ISSUE TITLE
Allow pages and posts to output to root directory

### ISSUE THREAD

**Issue by mingp** [cryogen-project/cryogen-core#32]
I think it would be preferable to allow the output of pages and posts to the root directory without an additional prefix like `posts` or `pages` for users who want it.

To be honest, I'm not entirely sure if this is meant to be possible with the current release of Cryogen. I didn't find mention of it in the docs, and when I tried setting the appropriate configs to empty, it ended up silently breaking the output rendering in some places. So, I'm not sure whether this should be a change to the docs or a change to the compiler.

What would need to change? How big of a change would this be? Could this be done in a backward compatible way? The configuration keys for `post-root` and `page-root` would need to be split out somehow, so that the post and page sources can live in separate directories and both output to the root directory. For backwards compatibility, my initial idea is: `post-root` and `page-root` determine input directories. If specified, `post-output-root` and `page-output-root` determine output directories. If unspecified, default to previous behavior.

I would be fine with making these changes and submitting a PR, if someone who is more familiar with the codebase could please clarify and confirm the above, as to avoid potentially going in the wrong direction with this.

Thanks!

**Comment by lacarmen** [comment]
If you do a PR I can look it over before merging but your idea is correct. You can specify default config values in the [`read-config` function](https://github.com/cryogen-project/cryogen-core/blob/master/src/cryogen_core/compiler.clj#L324)

**Comment by puredanger** [comment]
fwiw, I was just looking for this functionality too

**Comment by lacarmen** [comment]
Implemented in pull #56.
