### ISSUE TITLE
Add active page to config map

### ISSUE THREAD

**Issue by ciwchris** [cryogen-project/cryogen-core#35]
On some pages, like the home page, a key is added to the map so it can be used in templates to determine if it's the page currently being rendered. In complier.clj:

```
(render-file "/html/home.html"
                     (merge params
                            {:home    true
                             ...
```
And used in the base template: 
```
<div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li {% if home %} class="active" {% endif %}><a href="{{index-uri}}">Home</a></li>
```
I want to add a link to the tags page in the navigation bar, but there isn't a key added to the map for the tags page so there's no way to conditionally add the "active" class. A key could be added to the map, although I'm not sure of a name because "tags" is already used. Therefore I was thinking maybe the page name should be stored instead of a custom key with a boolean for each page. So compiler.clj would be like:
```
(render-file "/html/home.html"
                     (merge params
                            {:active-page    "home"
                             ...
```
And could be used like:
```
<ul class="nav navbar-nav">
    <li {% ifequal active-page "home" %} class="active" {% endifequal %}><a href="{{index-uri}}">pages</a></li>
```

Thoughts?

**Comment by lacarmen** [comment]
Makes sense to me, but I think the already existing booleans should be left in there for the users that have already adopted this method of setting their active pages.

**Comment by ciwchris** [comment]
Thanks! I created and was using a custom version, I'm glad I won't have to maintain it separately. I left the previous keys. Let me know if you'd like any changes to the approach I took. Would you like me to update the templates to use the new keys?

**Comment by lacarmen** [comment]
The PR looks fine, thanks! You don't need to make any changes to the template for now
