### ISSUE TITLE
SCSS compilation breaks watcher assumptions

### ISSUE THREAD

**Issue by j0ni** [cryogen-project/cryogen-core#7]
When you edit `scss` files in the `css` resources directory, the watcher notices the change in `sum-times` and triggers a re-compile. This causes `scss` files to be compiled to `css` files in the same directory, which causes a change in `sum-times`, triggering another re-compile.

I'm not exactly sure how this works. I was hacking on `scss.clj` and noticed that it set up an infinite loop, but when I backed out again to v0.1.9 of `cryogen-core`, I noticed it only compiles twice per save of a SCSS file. So I'm not exactly sure of the mechanism, and specifically why it stops re-compiling at all.

There's a few possible solutions here. The watcher could switch to using checksums rather than times. The compiler could stage compiled `css` outside the `templates` directory. etc.

**Comment by j0ni** [comment]
Looks like the infinite loop was actually a bug in my code, and since the `sass` compiler was writing to the `resources/public` directory, my explanation of the double compile thing was likely wrong.

I can only surmise that the `sass` compiler drops some tmp files into the source directory, or otherwise causes the modified times to be updated. Otherwise I can't see why it was happening. Either way, using checksums rather than modified times made it stop.

**Comment by lacarmen** [comment]
I just pushed out 0.1.11 to clojars :)

**Comment by lacarmen** [comment]
Can we close this one now?
