### ISSUE TITLE
Sitemap Generation Loc Broken on Windows

### ISSUE THREAD

**Issue by Artiavis** [cryogen-project/cryogen-core#73]
This is a pretty straightforward fix. The naive regex in sitemap.clj prevents this from working on Windows, because the paths are given in UNIX format. This shouldn't be too hard to fix, but unfortunately, there isn't anything like Python's [os.path.join](https://docs.python.org/2/library/os.path.html#os.path.join) and [os.path.split](https://docs.python.org/2/library/os.path.html#os.path.split) that I'm aware of. Could conceivably be "brute-forced" by switching on java.io.File#seperator, but might be cleaner to create helper methods using the java.io.File API directly.

https://github.com/cryogen-project/cryogen-core/blob/fb802035548bc936a87b6e6630f7d5959c7258b3/src/cryogen_core/sitemap.clj#L13-L14

**Comment by yogthos** [comment]
Since it is just one occurrence, I think just using `File/separator` would make sense:

```clojure
(str "resources" File/separator "public" File/separator)
```

**Comment by Artiavis** [comment]
[In the words of Jon Skeet, that string needs to be escaped too in order to work.](http://stackoverflow.com/a/10336327)

Something like...

````clojure
(import '[java.io File] '[java.util.regex Pattern])
(defn loc [^java.io.File f]
  (let [resources-pattern (Pattern/quote (str "resources" File/separator "public" File/separator))]
    (-> f (.getAbsolutePath) (.split resources-pattern) second)))
````

**Comment by lacarmen** [comment]
Closing this as cryogen-project/cryogen#133 is a duplicate and has been closed.
