### ISSUE TITLE
Commit 510c33c Fails to Compile on Windows 10

### ISSUE THREAD

**Issue by Artiavis** [cryogen-project/cryogen-core#74]
I pulled the latest Cryogen Core on Windows 10 and am unable to compile the code, but when I revert to the parent commit, I can.

https://github.com/cryogen-project/cryogen-core/commit/510c33c23d587f2b6d335689aff596a051a6346a

I assume that `(str ^java.io.File page)` calls `getPath` [as indicated in the JavaDocs](https://docs.oracle.com/javase/7/docs/api/java/io/File.html#getPath()), which appears to return the absolute path (at least) on my Windows machine.  Perhaps it returns a relative path on *nix machines?

Traceback looks something like...
````
clojure.core/pmap/fn/...
cryogen-core.compiler/read-posts/fn/...
cryogen-core.compiler/parse-post....
cryogen-core.compiler/parse-post-date....
java.text.DateFormat.parse...
java.text.ParseDateException: Unparseable date: "C:\Documen"
````

At any rate, and as I raised in https://github.com/cryogen-project/cryogen-core/issues/73, naive path regex does not appear portable in JVM languages. This should be reimplemented, perhaps in terms of the existing Java file API's?

**Comment by lacarmen** [comment]
Hey, I'm sorry for the super late reply. I must have lost track of this issue. 

I don't have a Windows machine so I wouldn't be able to test the fix, would you be up for doing a PR @Artiavis?

**Comment by tuhlmann** [comment]
@lacarmen I provided a PR that fixes that problem on Windows.
See #78

**Comment by lacarmen** [comment]
Just pushed out `0.1.44` with the fix above to Clojars.

**Comment by tuhlmann** [comment]
@lacarmen Thank you. The new config param `:sass-path` and `:compass-path` should probably also be described. Do you wanna integrate that or should I provide another PR?

**Comment by lacarmen** [comment]
If you're up for it then that would be great @tuhlmann

**Comment by tuhlmann** [comment]
Done @lacarmen

**Comment by lacarmen** [comment]
Closing this as cryogen-project/cryogen#133 is a duplicate and has been closed.
