### ISSUE TITLE
<!--more--> marker is not recognized

### ISSUE THREAD

**Issue by SVMBrown** [cryogen-project/cryogen-core#76]
I have tested with a blank install and changed the following files as follows:

resources/templates/config.edn
```
{...
  :blocks-per-preview 10
  :previews? true
 ...}
```
resources/templates/md/posts/docs.md
```{:title "Quick Start Guide"
 :layout :post
 :tags  ["cryogen"]
 :toc true}

This intro only documents a subset of Cryogen's features. For additional documentation please see the [cryogen site](http://cryogenweb.org).
<!--more-->
## Features
...
```

The blog index page looks as follows (clearly not cutting off after the first line)

![cropped-cryogen](https://cloud.githubusercontent.com/assets/9145322/21118258/16461456-c08b-11e6-82c2-d9a051ad21c4.png)

Please let me know if I have done something incorrect here which is causing the marker to not be recognized.

Thanks!

**Comment by SVMBrown** [comment]
This is strange behaviour with the markdown-clj library, it seems that `<!more>` emits `<!--more-->`, but still doesn't work as a marker, `<!-more->` emits `<!---more--->` and works as a marker somehow, and `<!--more-->` emits `<!--&ndash;more&ndash;-->`...

**Comment by lacarmen** [comment]
Interesting... perhaps something for @yogthos to look at? Good thing is that `<!-more->` works.
