### ISSUE TITLE
Schema validation for the config

### ISSUE THREAD

**Issue by yogthos** [cryogen-project/cryogen-core#88]
Cryogen can give poor errors when the configuration is invalid. Schema or Spec should be used to validate the configuration when compiling and provide meaningful errors to the user. The configuration options can be found [here](http://cryogenweb.org/docs/configuration.html).

**Comment by jerger** [comment]
cool idea - I'm using schema heavily on my DevOps-System dda-pallet (e.g. https://github.com/DomainDrivenArchitecture/dda-managed-ide/blob/master/src/org/domaindrivenarchitecture/pallet/crate/managed_ide.clj). I'm interested in discussion & helping :-)

Do you've an fork, we can collaborate & start work on (my own fork is blocked by a non finished pull request at the moment) ?

**Comment by yogthos** [comment]
I don't have a fork for this yet. I was thinking the main goal would be to ensure that the config is in a good state when the compiler runs, and to catch any configuration errors early on so that a meaningful error can be displayed. Would probably be the easiest to validate it [here](https://github.com/cryogen-project/cryogen-core/blob/d502799a9354f70d782bd35d4ff979f08773bfa4/src/cryogen_core/compiler.clj#L446) as it's read.

**Comment by jerger** [comment]
exactly ... 

If you want to choose schema, we will define a config schema and switch on output validation for read-config function - I often used this so we will get this up and working very fast.

But we can also give the new spec a try, if cryogen-core will run on clojure 1.9alpha. I never used spec but I'm open to learn sth. new :-)

What should we choose?

**Comment by lacarmen** [comment]
I personally prefer schema over spec so that's what I'd like to go with.

**Comment by yogthos** [comment]
My vote would be for Schema as well.

**Comment by lacarmen** [comment]
Completed in `0.1.53`
