### ISSUE TITLE
Globally available data services in template contexts.

### ISSUE THREAD

**Issue by emidln** [cryogen-project/cryogen-core#93]
I'd like some way of defining data that is generated at build time and then made available to various templates. I know I can fork cryogen-core and hack something in each time, but it'd be nice to say something like

:custom-data-providers {:my-key :my-namespace/some-func}

And then be able to write a template that presumed the existence of my-key.

I'll probably hack this in for myself, but is there any interest on standardizing something like this?

**Comment by lacarmen** [comment]
Probably not, as I don't see this being a common enough use case and I'd rather keep that data-generating step separate from Cryogen.

**Comment by bagdemir** [comment]
I need something similar. It would be nice to have the ability to add some custom post/page metadata, like 
```
{
 :title "My article", 
 :shortdesc "This article is about generating static sites, etc. etc."
}
```
which I can use in the "archive" page template, later.

**Comment by lacarmen** [comment]
@bagdemir That's actually pretty easy to accomplish. I would just have to remove the `select-keys` from [this line](https://github.com/cryogen-project/cryogen-core/blob/master/src/cryogen_core/compiler.clj#L189) and all your post metadata could be made available. 

I believe @emidln is talking about data generated from a function that he writes himself, not the data from the static site. (Do correct me if I'm wrong though)

**Comment by emidln** [comment]
Static data is actually already available if you put it in the config.edn.
What I'd like is the ability to define a function whose results would be
available in the template contexts. I think this is actually very easy to
do, basically its a temple context middleware. If we wrap the render-file
from selmer, it could evaluate some functions if available and merge into
the context. To @bagdemir's point, it would be then trivial to reuse the
functions which parse pages to grab misc metadata and do some calculation.

On Apr 10, 2017 9:32 PM, "Carmen La" <notifications@github.com> wrote:

@bagdemir <https://github.com/bagdemir> That's actually pretty easy to
accomplish. I would just have to remove the select-keys from this line
<https://github.com/cryogen-project/cryogen-core/blob/master/src/cryogen_core/compiler.clj#L189>
and all your post metadata could be made available.

I believe @emidln <https://github.com/emidln> is talking about data
generated from a function that he writes himself, not the data from the
static site. (Do correct me if I'm wrong though)

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/cryogen-project/cryogen-core/issues/93#issuecomment-293132593>,
or mute the thread

**Comment by lacarmen** [comment]
Ah okay so I understood you correctly then. 

Yeah, that's not a step that I want to have embedded into Cryogen's compilation process. @bagdemir's case can be easily solved though.

**Comment by lacarmen** [comment]
@bagdemir please open a separate issue for your issue if you'd like it addressed.
