### ISSUE TITLE
Need changes to add Lotus theme

### ISSUE THREAD

**Issue by KingMob** [cryogen-project/cryogen-core#96]
OK @lacarmen, I wrapped up the changes I wanted to make, and set about adding the files to cryogen. As soon as I did, though, I ran into a few issues that earlier themes don't have:

1. My theme requires Sass, but the `css` dir under a theme isn't automatically run through sassc.
2. My theme has images, in particular, a social icons SVG. `copy-resources-from-theme` doesn't copy the theme's `img` dir.

I opened this issue to get your feedback before proceeding. I see a few options, but I'm open to whatever you like:

1. I change nothing but add a README in the theme directory, instructing people how to update the `:resources` and `:sass-src` keys to get the theme working. Simple, but a crappy experience, since people won't read it.
2. I add `img` to the default list of theme directories copied, and create empty `img` dirs in the existing themes to prevent breaking. For Sass, I add the public `css` folder as a default, and reorder Sass compilation to happen after the resources are copied over.
3. Give themes a `config.edn` of their own where they can add entries to the existing config to specify what they need.

I think option 3 is the most future-proof and elegant. Thoughts?

**Comment by lacarmen** [comment]
> I think option 3 is the most future-proof and elegant.
I agree. So you're thinking of merging the configs at the start of compilation then?

**Comment by KingMob** [comment]
Yeah, I need to dive into the code more to learn precisely where to put that. I know there's some docs on user-specified overrides (like for secrets), so we probably want to merge a theme config before then. 

The only mildly tricky part is you have to read the main config, determine the theme, check for a theme config, and merge that if it exists, *before* you do anything else with the config, since entries can be added. 

Anyway, I'll take a look this afternoon. Any suggestions/directions welcomed 😄

**Comment by lacarmen** [comment]
Sounds good to me! Don't hesitate to reach out if you have more questions :)
