### ISSUE TITLE
Refactor project structure to be less deep

### ISSUE THREAD

**Issue by lacarmen** [cryogen-project/cryogen-core#98]
Get rid of the `resources` directory and just have `public` and `templates` on the top level.

/resources/public -> /public
/resources/templates -> /templates

Perhaps themes should be a top level directory as well? (I'm not sure about this one yet)

**Comment by madstap** [comment]
Taking a cue from [hugo](https://gohugo.io/content-management/organization/), how about a `content` directory with `/content/pages` and `/content/posts/`? That could allow for a clean way to add other types of content in the future/in specific themes/with specific configuration and uses familiar terminology from the cms world.

**Comment by lacarmen** [comment]
@madstap Sounds good to me!
