### ISSUE TITLE
Support TOCs with inline `code`

### ISSUE THREAD

**Issue by kyptin** [cryogen-project/cryogen-core#99]
If I have backtick-delimited `code` in a heading, the table of contents is broken.

Here's a small reproducible test case. With the following post markdown:

```
{:title "A Cryogen feature request: TOCs that include headings with backticks"
 :layout :post
 :tags ["cryogen"]
 :toc true}

## A heading without code

## A heading with some `code` included

## Another heading without code
```

I see the following rendering. Note that the middle item in the table of contents does not match its heading.

![toc with inline code](https://user-images.githubusercontent.com/254619/29851159-9d2c44bc-8d00-11e7-92c1-54e3455ff90a.png)

Thanks for your work on Cryogen, by the way. It looks pretty neat. :smile:

**Comment by madstap** [comment]
I tracked down the source of the issue, but I don't really grok zippers and the `cryogen-core.toc` namespace. I would love some input on this [WIP commit](https://github.com/madstap/cryogen-core/commit/465ea3c4cbf10a6a4d7989a55ec2a5119bf94e61).

**Comment by lacarmen** [comment]
Unfortunately (or fortunately?) much of the `cryogen-core.toc` namespace was not written by me so it would take me some time to go through it. I'll try to comment on your commit if I find a chance. Thanks for your help on this issue 😄

**Comment by madstap** [comment]
I rebased the commit and made a PR. Should be easier to comment on.

**Comment by lacarmen** [comment]
@kyptin I pushed out a new version of `cryogen-core` to clojars (0.1.60) with @madstap's fix. Hope that works for you!

**Comment by kyptin** [comment]
@lacarmen - Thanks very much!
